build_error: fix missing normalization for inline scopes
Similar to other instances, inline scope instance is also polymorphic in
MIR and it needs to be normalized before we can call queries that expect
normalized instances.